comp:
	g++ CDiscretization.cpp CFluido.cpp CLiquido.cpp CGas.cpp CMatrix.cpp CGnuplot.cpp CGrid.cpp CProps.cpp CReservoir.cpp CWell.cpp CSimuladorMonofasico2D.cpp main.cpp

exe:
	./a.out

compexe:  comp exe

clean:
	rm *.o *.obj *.exe a.out
